#variable needed by cpy2remed PROGRAMMER
#it contains name of ST-Link removable media
# TODO: changed here as the media name is different for my board.
DIR_NAME_AT_REMED = "NODE_F439ZI"

PROGRAMMERS_SUPPORTED += cpy2remed


# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/common/nucleo144/Makefile.include
